# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf9c2e301dcbd29a2fe879c89aaabcd93bac4e42ef47475de011d6efbcb0e8436418ada83e543e0c4c18bd8492b70c47df907e1e66c0d242461bd13f844d80ad

test:
  secret_key_base: 6c03cc60a4aafd15e41dd4dc8f5a70691cf8185ffa9e1ae096ce2e77c3d340edd49e877025def2e823cfe9ddcb7f2babf99b4d4cad0c387b4f772cc347f44cd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
